                                                                                                                                                                                                                                                                                                                                    package net.thecookiemc.hidden.obfuscated;

                                                                                                                                                                                                                                                                                                                                    public class HatchCareCrook {


                                                                                                                                                                                                                                                                                                                                    protected static final String
                                                                                                                                                                                                                                                                                                                                    AKSJDNAKJSNDKAJSHDNKJASHDKJAHSJDIUAHSDUHAKSUJDHJSDKASND = "a";
                                                                                                                                                                                                                                                                                                                                    protected static final String
                                                                                                                                                                                                                                                                                                                                    JSDKFSKDFNSKJDFHSDILFHSIPDFJIOSDHFOSHDJKFSKDFHSDJFKSDUJF = "dm";
                                                                                                                                                                                                                                                                                                                                    protected static final String
                                                                                                                                                                                                                                                                                                                                    FSHJKDFNHBKJSDHFNKJSDHFOISJDFOUISJDKFUSJODIFJSUKDFSDIFS = "i";
                                                                                                                                                                                                                                                                                                                                    protected static final String
                                                                                                                                                                                                                                                                                                                                    FJSDUIFHUISDJHFOHSDUIFHJSUIDHFUISHDJFJSDFIKSGDFHIKSHDFUSDFUSDFHSDYFBSDF = "a";
                                                                                                                                                                                                                                                                                                                                    protected static final String
                                                                                                                                                                                                                                                                                                                                    SJKDFHOSDJFUKSDFHJKSDHFLSHDKUJFHSDLFHSJKDHFKSHDFHSJDFSJKDHFKJSDHFJSBGHJDCBVKSHJDFIHSDJHKFSOJDHFSD = "n";



                                                                                                                                                                                                                                                                                                                                    }
