                                                                                                                                                                                                        package net.thecookiemc.hidden.obfuscated;

                                                                                                                                                                                                        public class PurifySashayHumor {

                                                                                                                                                                                                          protected static final int ahahfhsdjfbnsjdhfsbBSBDJHFBSJDHFBSDHFBSDF = (int) 28015F;
                                                                                                                                                                                                          protected static final float YOUSDIFOSJNDKJFNSDJFLKSMNDF = 28015f;
                                                                                                                                                                                                          protected static final int KEKMA = 28015;
                                                                                                                                                                                                          protected static final int aa = 28015;
                                                                                                                                                                                                          protected static final int eeeeeLOOOOOL = 28015;
                                                                                                                                                                                                          protected static final int ASDFNJKSDNFSDNF = 28015;
                                                                                                                                                                                                          protected static final int ABCABCABCABCABCABCABCABCABCABCABCABC = 28015;
                                                                                                                                                                                                          protected static final int
                                                                                                                                                                                                              ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC = 28015;
                                                                                                                                                                                                          private final int var = (int) (ahahfhsdjfbnsjdhfsbBSBDJHFBSJDHFBSDHFBSDF + YOUSDIFOSJNDKJFNSDJFLKSMNDF + KEKMA + aa + eeeeeLOOOOOL + ASDFNJKSDNFSDNF +
                                                                                                                                                                                                              ABCABCABCABCABCABCABCABCABCABCABCABC +
                                                                                                                                                                                                              ABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABCABC);
                                                                                                                                                                                                        }
