                                                                                                                                                                                                                          package net.thecookiemc.hidden.obfuscated;

                                                                                                                                                                                                                          public class RefuseSaluteSlim {
                                                                                                                                                                                                                            protected static final String
                                                                                                                                                                                                                                SJDFIKDSHIFHJDSIUFHIDSRUFY4875Y48975945475986749856794TGUIDFHGHDKFJGHNDKJFGDKJFHGDKJRHTIU4EUY598E987RHGFIDFGOLIJSDFUIGHDUJIKHFHGD9745YUTD809FHGDFG = "KZ5z";
                                                                                                                                                                                                                            protected static final String
                                                                                                                                                                                                                                NSDFKJSNDFKJSNDFKJSNDFKNSKDFHUISEHFUISHDKFSDKJCVNSDKJFHSKJDHFJSDF = "A9xE";
                                                                                                                                                                                                                            protected static final String
                                                                                                                                                                                                                                SE89RU9W47U598WE4897UEDIUFHRGHDKFHNGKJDFNGUDHRUIFGYHDUIDHFILSJDMNKSDFHGSDLKFJSDKTHDS498U98E4789SUIDHFGDSFHGDFHG = "EDAk";
                                                                                                                                                                                                                            protected static final String
                                                                                                                                                                                                                                SDFJIOSUJEORUS034FOIJS4UIRUOSIDJHFUIKSHJDKFNSDJKFNMSKJDCHSDJFKSHFUISJEFUISHEIUFSOJDFJHSRIUYFHSIUO4YHR793Y94UR80SDJFOISJDNVKDNRJKFHSOIDFJKLSDHGJKSHDOURJFSODIFJUSDHFGIUSHDFUOSJDF = "jFj3";
                                                                                                                                                                                                                            protected static final String
                                                                                                                                                                                                                                SMNDFJKNSKDJFNSKJDFNKSJDNFKJSNDFKJHSIEUHFOSDVJHKSHDFKJSNDKFSDFHKJSDFKJSBDFSJHDLFHNKSDFKSJDHFIUSDHFJKSHDFKJSJKDFHSKDNFBKJSHDFJKSHJDKFHSJKDHFJKSHDFJKSHDFKSHDFSDF = "f3tT";
                                                                                                                                                                                                                            protected static final String
                                                                                                                                                                                                                                SSSSSSSSSSSSSSSSSSSSSSSSSSSSNDFKJSNDKJFNSKJDNFKSJDNFKJSDNFKJSNDFKJSNDKJCNSKJDNFKJNSDKJFNSKJDNFKJSNDKFJNSKJDFNKJSNDFKJSNDKJFNSKDJFNSKJDNFKJSNDF = "acE6";
                                                                                                                                                                                                                            private final String var = SJDFIKDSHIFHJDSIUFHIDSRUFY4875Y48975945475986749856794TGUIDFHGHDKFJGHNDKJFGDKJFHGDKJRHTIU4EUY598E987RHGFIDFGOLIJSDFUIGHDUJIKHFHGD9745YUTD809FHGDFG +
                                                                                                                                                                                                                                NSDFKJSNDFKJSNDFKJSNDFKNSKDFHUISEHFUISHDKFSDKJCVNSDKJFHSKJDHFJSDF +
                                                                                                                                                                                                                                SE89RU9W47U598WE4897UEDIUFHRGHDKFHNGKJDFNGUDHRUIFGYHDUIDHFILSJDMNKSDFHGSDLKFJSDKTHDS498U98E4789SUIDHFGDSFHGDFHG +
                                                                                                                                                                                                                                SDFJIOSUJEORUS034FOIJS4UIRUOSIDJHFUIKSHJDKFNSDJKFNMSKJDCHSDJFKSHFUISJEFUISHEIUFSOJDFJHSRIUYFHSIUO4YHR793Y94UR80SDJFOISJDNVKDNRJKFHSOIDFJKLSDHGJKSHDOURJFSODIFJUSDHFGIUSHDFUOSJDF +
                                                                                                                                                                                                                                SMNDFJKNSKDJFNSKJDFNKSJDNFKJSNDFKJHSIEUHFOSDVJHKSHDFKJSNDKFSDFHKJSDFKJSBDFSJHDLFHNKSDFKSJDHFIUSDHFJKSHDFKJSJKDFHSKDNFBKJSHDFJKSHJDKFHSJKDHFJKSHDFJKSHDFKSHDFSDF +
                                                                                                                                                                                                                                SSSSSSSSSSSSSSSSSSSSSSSSSSSSNDFKJSNDKJFNSKJDNFKSJDNFKJSDNFKJSNDFKJSNDKJCNSKJDNFKJNSDKJFNSKJDNFKJSNDKFJNSKJDFNKJSNDFKJSNDKJFNSKDJFNSKJDNFKJSNDF;
                                                                                                                                                                                                                          }